### PR TITLE
Refactor BinarySearchTree (BST) methods

### PR DESCRIPTION
**Pull request by kubkon**
I've simplified insert and find methods somewhat with a Haskell-like use of guards. Have a look and let me know what you think!

### CODE REVIEW

**Comment by alisdair** [comment]
I think overall this approach is probably better. I have some questions about semantic changes, especially about multiple inserts, and some style nits.

**Comment by kubkon** [comment]
The multiple inserts is my mistake (I've blindly copied the code from my toy project today). I was following the ideas from Cormen's book and initially assumed multiple items to be valid. I was meant to rectify this but in the end forgot. I'll push a change tomorrow.

**Comment by kubkon** [comment]
I've addressed the comments. Let me know what you reckon!

**Comment by alisdair** [comment]
yes

**Comment by kubkon** [comment]
:dancer: :grinning:

**Comment by alisdair** [comment]
I think it's much clearer than the imperative implementation. But now I'm looking at how similar find and insert are and wondering about playing with macros or higher-order functions for traversal… curses! :stuck_out_tongue:

**Comment by kubkon** [comment]
Hah! You noticed that as well, did you!

**Pull request merged**
